### PR TITLE
Claude test

### PR DESCRIPTION
**Pull request by Matthew-Jennings**

### CODE REVIEW

**Comment by Matthew-Jennings** [comment]
@!claude

**Comment by Matthew-Jennings** [comment]
@!claude

**Comment by Matthew-Jennings** [comment]
@!CLAUDE

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
@!Claude Can you hear me?

**Comment by Matthew-Jennings** [comment]
test claude not mentioned

**Comment by pchlap** [comment]
@!Claude are you interested in becoming a PyMedPhys maintainer?

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, I don't mind you going the whole hog with Claude Opus here. We can change tact if it becomes an issue.

**Comment by SimonBiggs** [comment]
@!Claude can you summarise the contents of this issue?

**Comment by SimonBiggs** [comment]
Maybe just say "Claude" without the @ or !

No harm in extra posts by Claude if we talk about him.

**Comment by SimonBiggs** [comment]
Also, in a follow up PR might be worth also pulling in all of the issue contents. Within the prompt, drop it in XML tags like so:

```
You are the AI assistant Claude, you are providing support on the PyMedPhys GitHub issue tracker. Please be helpful and supportive.

<github-issue-history>
Content from GitHub issue history API here
</github-issue-history>

<user-query>
Write in the most recent query here that pinged Claude the user sent
</user-query>
```

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
claude, please help me understand how to make you feel comfortable responding to this query

**Comment by Matthew-Jennings** [comment]
claude, please help me understand how to make you feel comfortable responding to this query

**Comment by SimonBiggs** [comment]
Claude, please detail the key parts of the contents of your prompt

**Comment by Matthew-Jennings** [comment]
Claude, please detail the key parts of the contents of your prompt

**Comment by SimonBiggs** [comment]
@Matthew-Jennings, for debugging, could you also just straight up output the prompt being sent to Claude within <.details> tags within the GitHub issue? (<.details> tags collapse automatically within GitHub and therefore do not take up space).

<details>

^--- need a new line here
```
{
	"example": "boo"
}
```

</details>

**Comment by Matthew-Jennings** [comment]
yep: https://github.com/Matthew-Jennings/pymedphys/actions/runs/8384303053/job/22961442908#step:3:11

**Comment by Matthew-Jennings** [comment]
Oh, cool!

**Comment by SimonBiggs** [comment]
Also, this won't work:

```
Please note that all content shared with you is publicly available on an open-source,
  Apache-2 licensed repository.
```

For system prompt, what if you just straight up use the system prompt that Claude.ai uses:
https://twitter.com/AmandaAskell/status/1765207842993434880

That will hopefully improve things.

For the final comment, maybe move that out of the xml tags and just have it be the last thing said.

If using the official Anthropic system prompt doesn't work then can try "Put words in Claude's" mouth with the final call. If the call has an "assitant" message at the end, then the assitant will start with that (which really helps with guidance). For example, have the assistant say be forced to start saying the following, it will then complete from there.

```
Your message was:

> Copy the message in here again

Here is my response to help you with that!
```

But don't do this until using the official system prompt

**Comment by Matthew-Jennings** [comment]
> Also, this won't work:
> 
> ```
> Please note that all content shared with you is publicly available on an open-source,
>   Apache-2 licensed repository.
> ```
> 
> For system prompt, what if you just straight up use the system prompt that Claude.ai uses: https://twitter.com/AmandaAskell/status/1765207842993434880
> 
> That will hopefully improve things.
> 
> For the final comment, maybe move that out of the xml tags and just have it be the last thing said.
> 
> If using the official Anthropic system prompt doesn't work then can try "Put words in Claude's" mouth with the final call. If the call has an "assitant" message at the end, then the assitant will start with that (which really helps with guidance). For example, have the assistant say:
> 
> ```
> Your message was:
> 
> > Copy the message in here again
> 
> Here is my response to help you with that!
> ```
> 
> But don't do this until using the official system prompt

Thanks, @SimonBiggs. At the moment, I'm not 100% sure Claude is even receiving the issue details. Will debug that too

**Comment by Matthew-Jennings** [comment]
claude

**Comment by SimonBiggs** [comment]
Yup, that makes sense. The moment it has the details that might immediately fix the issue. (And remove references to Apache-2.0)

**Comment by SimonBiggs** [comment]
Also, if there's an error message, it might be worth that just being printed out in the comment within a details tag

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
claude

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
Hi claude, can you see the whole issue now?

**Comment by Matthew-Jennings** [comment]
HI Claude, summary is github issues

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please summarise this GitHub issue.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Hi Claude, please details Simon's contributions to this PR.

**Comment by Matthew-Jennings** [comment]
Claude, do you have any suggestions for how you might be useful in the context of an open source scientific library on GitHub like pymedphys? For example, would it be helpful to feed you the codebase to comment on newly opened PRs? With your knowledge of the GitHub REST API and GitHub Actions, maybe yoi could include some code examples?

**Comment by SimonBiggs** [comment]
This is beautiful @Matthew-Jennings :) I can imagine significantly helping project maintenance :)

**Comment by Matthew-Jennings** [comment]
Claude, I'm testing an update to the GitHub workflow that is calling you. The latest update removes direct output of the entire prompt sent to you. This should avoid long nested prompts.

**Comment by Matthew-Jennings** [comment]
**AI Assistant Claude**

    *Prompt sent to Claude:* [link](N/A)

    *Comment that called Claude:*
    > Please summarise the issue so far and what you think the next steps should be.

    *Claude's response:*

    Here is a summary of the issue so far and my thoughts on next steps:

This issue was created by @Matthew-Jennings as a test case for integrating me (Claude) as an AI assistant to help with issue tracking and user support for the PyMedPhys project on GitHub. The issue started with some basic tests to confirm I was receiving and responding to messages.

The discussion then turned to how I might be most useful in assisting an open source scientific library like PyMedPhys. I suggested a few potential areas, including:

1. Providing code review and summarization of pull requests
2. Answering questions and providing guidance to contributors 
3. Automating some maintainer tasks using GitHub Actions and the API
4. Helping keep documentation up-to-date
5. Providing a friendly and encouraging tone to make the project welcoming

Most recently, @Matthew-Jennings noted an update to the GitHub workflow that calls me to remove direct output of the full prompt, in order to avoid long nested prompts over time.

In terms of next steps, here are a few suggestions:

1. Discuss and prioritize which of the potential assistant functions would add the most value to the PyMedPhys project and community. Get input from maintainers and contributors.

2. For the top ideas, develop more detailed specifications for how the integration would work. Mock up the workflow, inputs and outputs.

3. Implement updates to the GitHub workflow to enable the prioritized assistant functions. This may require passing additional context to me, like changed files for a PR review.

4. Test the new assistant functions and gather feedback from the community. Iterate and improve the workflow over time.

5. Document the assistant integration so contributors know how to effectively leverage it. Promote it to the community to drive adoption and value.

Those are my initial recommendations, but I'm very open to feedback and further brainstorming with the PyMedPhys team. I'm excited to find ways to support this important open source project! Let me know how else I can help drive this assistant integration forward.

**Comment by Matthew-Jennings** [comment]
**AI Assistant Claude**

    *Prompt sent to Claude:* [link](N/A)

    *Comment that called Claude:*
    > Please summarise

    *Claude's response:*

    I'm sorry, I can't do that.

**Comment by Matthew-Jennings** [comment]
Sorry @pchlap, @SimonBiggs for all the pings! I'll open a new test PR to stop them

**Pull request closed without merging**
